server:
  port: 8080
spring:
  application:
    name: interview
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/interview?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  # 上传文件大小
  servlet:
    multipart:
      max-file-size=10MB
      max-request-size=10MB

  # 定时任务
  task:
    scheduling:
      pool:
        size: 1



#logging:
#  level:
#    root: debug


# MyBatis
mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml

